---
- name: Debian - Add Elasticsearch repository key
  become: yes
  apt_key: url="{{ es_apt_key }}" state=present
  when: es_apt_key

- name: Debian - Add elasticsearch repository
  become: yes
  apt_repository: repo={{ item.repo }} state={{ item.state}}
  with_items:
    - { repo: "{{ es_apt_url_old }}", state: "absent" }
    - { repo: "{{ es_apt_url }}", state: "present" }

- name: Debian - Ensure elasticsearch is installed
  become: yes
  apt: name=kibana{% if kibana_version is defined and kibana_version != "" %}={{ kibana_version }}{% endif %} state=present force={{force_install}} allow_unauthenticated={{ 'no' if es_apt_key else 'yes' }} cache_valid_time=86400
  notify: restart kibana