---
- set_fact: use_system_d={{(ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('8', '>=')) or (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version | version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('15', '>=')) }}
- set_fact: instance_init_script={{init_script | dirname }}/{{init_script | basename}}
- set_fact: instance_sysd_script={{sysd_script | dirname }}/{{sysd_script | basename}}
  when: use_system_d

- name: Include specific Elasticsearch
  include_tasks: kibana-Debian.yaml
  when: ansible_os_family == 'Debian'
- name: Include specific Elasticsearch
  include_tasks: kibana-RedHat.yaml
  when: ansible_os_family == 'RedHat'

- name: Configure Kibana
  template: 
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
  notify:
    - restart kibana
